### ISSUE TITLE
<card> tags break, possibly before headings

### ISSUE THREAD

**Issue by tf13** [imdone/imdone#64] opened 2021-03-11 18:02 UTC
**Describe the bug**
Using the `<card> </card>` tags doesn't preserve line breaks in some circumstances.

**To Reproduce**

1. Create a card with the following content, and it renders properly in imdone:

```
# [\<card\> tag breakage](#TODO:0)
<card>
@www @rrr #ttt #ccc #iii
*Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.*
## heading 1
- lorem ipsum (dolore magna aliqua)
- dolor sit amet (dolore magna aliqua)
- consectetur adipiscing (dolore magna aliqua )
- elit sed do (dolore magna aliqua )
- tempor incididunt (dolore magna aliqua)
## heading 2
- <https://imdone.io/docs/#/cards?id=preserving-line-breaks>
- <https://imdone.io/docs/#/editors>
- <https://imdone.io/docs/#/editors?id=card-editor-keyboard-shortcuts>
<!--
modified:2021-03-11T12:46:44.084883
-->
</card>
```

2. Now insert a blank line before each of the level-2 subheadings and before the comment at the end:

```
# [\<card\> tag breakage](#TODO:0)
<card>
@www @rrr #ttt #ccc #iii
*Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.*

## heading 1
- lorem ipsum (dolore magna aliqua)
- dolor sit amet (dolore magna aliqua)
- consectetur adipiscing (dolore magna aliqua )
- elit sed do (dolore magna aliqua )
- tempor incididunt (dolore magna aliqua)

## heading 2
- <https://imdone.io/docs/#/cards?id=preserving-line-breaks>
- <https://imdone.io/docs/#/editors>
- <https://imdone.io/docs/#/editors?id=card-editor-keyboard-shortcuts>


<!--
modified:2021-03-11T12:46:44.084883
-->
</card>
```

3. View card in imdone. The card is truncated at the first blank line before a level-2 heading. In addition, if you eliminate those blank lines, but leave one before the comment, the modified meta tag doesn't seem to be read by imdone.

**Expected behavior**
The blank lines inserted before the headings should be rendered in imdone when they are between `<card> </card>` tags.

**Screenshots**

**Without blank lines**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/16142258/110832850-c5677200-8269-11eb-9ed7-c97898728c88.png">

**With a blank line before the first subheading**
<img width="265" alt="image" src="https://user-images.githubusercontent.com/16142258/110832952-dfa15000-8269-11eb-8962-482b3cf0325d.png">

**With a blank line before the second subheading**
<img width="263" alt="image" src="https://user-images.githubusercontent.com/16142258/110833208-33ac3480-826a-11eb-8df7-562c057e5db5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Imdone Version 1.12.0 (1.12.0)

**DoD**
- [x] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by tf13** [comment] 2021-03-11 18:06
Looks like inserting a non-breaking space (`&nbsp;`) on the "blank" line will preserve them. But that's true also without the `<card> </card>` syntax.

**Comment by piascikj** [comment] 2021-03-14 13:40
I can't reproduce this error.  What OS and version of imdone are you on?

**Comment by tf13** [comment] 2021-03-16 18:05
Upgraded to 1.13.1, and the `<card> </card>` syntax seems to work as expected. The one possible glitch is that when I use the in-app card editor, add the tags, save and close the editor, and then reopen, sometimes the closing `</card>` tag appears to be missing. I think it's still there but just not displayed, because if I replace it and reopen, I have two closing tags. Haven't tried all the permutations however.

**Comment by piascikj** [comment] 2021-03-18 15:00
The card tags are managed by imdone, so if you're using the in-app editor, don't add them.  But if you're modifying the file directly, then you'll have to put them in to preserve blank lines.

**Comment by piascikj** [comment] 2021-04-01 04:34
@tf13 Can we close this issue?

**Closed** 2021-04-06 17:04 UTC
Labels: bug
